<a href="https://colab.research.google.com/github/bhakya01/numpy.py/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [ ]:


temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# Convert Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32

# Find maximum, minimum, and mean
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Temperatures in Fahrenheit:", temperatures_f)
print("Maximum Temperature:", max_temp, "°C")
print("Minimum Temperature:", min_temp, "°C")
print("Mean Temperature:", mean_temp, "°C")




Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1 °C
Minimum Temperature: 20.8 °C
Mean Temperature: 23.542857142857144 °C


In [ ]:
first_three=(temperatures_w1[:3])
last_two=(temperatures_w1[-2:])
middle=(temperatures_w1[2:5])
print(last_two)
print(middle)
print(first_three)

[24.8 21.9]
[20.8 23.4 26.1]
[22.5 25.3 20.8]


In [ ]:
# 2D array
temperatures=([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]]


In [ ]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)

(2, 7)
float64
14


In [ ]:
week1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
week2=np.array([19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1])
week_end=week1[-2:]
week_end1=week2[-2:]
print(week_end)
print(week_end1)

[24.8 21.9]
[22.8 20.1]


In [ ]:
import pandas as pd

marks = pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
Ranks=np.random.randint(0,100,size=5)

In [ ]:
print("\nTop 3 Ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])


Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print(marks.iloc[2])

89


In [ ]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


In [ ]:
marks.loc['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
marks=marks.drop('Rank5')
cgpa=marks/10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],


    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'],


    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions)
print("\nHead:")
print(transactions.head())
print("\n Tail:")
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

 Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        C

In [ ]:
print("\n shape:")
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)
print(transactions[['ProductCategory','Amount']])


 shape:
(10, 4)
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
print(transactions.iloc[::-3])

   TransactionID ProductCategory Region  Amount
9            110     Electronics  North     400
6            107       Furniture   East     300
3            104       Furniture   East     450
0            101     Electronics  North     200


In [ ]:
filter=transactions[(transactions['Region']=='North')&(transactions['Amount']>250)]
print(filter)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
9            110     Electronics  North     400


In [ ]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [ ]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
transactions = transactions[transactions['TransactionID']!=109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions = transactions.drop('Discount',axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
